name: Build and Release
## Workflow: .github/workflows/build.yml  -- 03.10.2024 -- Ralph Roth
## See also: https://github.com/actions/runner-images/issues/10636 / Ubuntu-latest workflows will use Ubuntu-24.04 image
## https://github.com/actions/runner-images/blob/main/README.md#available-images

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.2.0
      - '1.*' # semantic versioning?

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner for cross-compilation

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'  # Set Go version // same as we have

    - name: Build for Windows (32-bit)
      run: |
        mkdir -p build
        GOOS=windows GOARCH=386 go build -o build/rupdater.exe main.go

    - name: Build for Linux (32-bit)
      run: |
        GOOS=linux GOARCH=386 go build -o build/rupdater main.go

        # Unable to resolve action gh actions/create-release, repository not found. Unable to resolve action gh actions/upload-release-asset, repository not found
    - name: Create release and upload artifacts
      id: release
      #uses: gh actions/create-release@v1
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: "Release for version ${{ github.ref }}"
        draft: false
        prerelease: false

    - name: Upload Windows binary
      # uses: gh_actions/upload-release-asset@v1
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: build/rupdater.exe
        asset_name: rupdater.exe
        asset_content_type: application/octet-stream

    - name: Upload Linux binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: build/rupdater
        asset_name: rupdater
        asset_content_type: application/octet-stream

    - name: Upload README.md
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: README.md
        asset_name: README.md
        asset_content_type: text/plain
