name: Build and Release
## Workflow: .github/workflows/build.yml  -- 03.10.2024 -- Ralph Roth
## See also: https://github.com/actions/runner-images/issues/10636 / Ubuntu-latest workflows will use Ubuntu-24.04 image
## https://github.com/actions/runner-images/blob/main/README.md#available-images

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.2.0
      - '1.*' # semantic versioning?

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner for cross-compilation

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25'  # Set Go version // same as we have

    - name: Build for Windows (32-bit)
      run: |
        mkdir -p build
        GOOS=windows GOARCH=386 go build -o build/rupdater.exe main.go

    - name: Build for Linux (32-bit)
      run: |
        GOOS=linux GOARCH=386 go build -o build/rupdater main.go

    - name: Create release and upload artifacts
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create "$GITHUB_REF_NAME" \
          --title "Release $GITHUB_REF_NAME" \
          --notes "Release for version $GITHUB_REF_NAME" \
          build/rupdater.exe \
          build/rupdater \
          README.md
