# GitHub Action Workflow: .github/workflows/go-lint.yml -- 04.10.2024 -- Ralph Roth

name: Go Lint and Test

on:
  push:
    branches:
      - main   # Trigger this workflow on pushes to the `main` branch.
  pull_request:
    branches:
      - main   # Trigger this workflow for pull requests targeting the `main` branch.

jobs:
  lint-and-test:
    runs-on: ubuntu-latest  # Run on Ubuntu (you can change to other environments if needed)

    strategy:
      matrix:
        go-version: [1.18, 1.19] # Specify the Go versions you want to test against

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }} # Use the matrix variable  # You can change the Go version if necessary

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/.golangci-lint-cache
          ./vendor
        key: go-mod-cache-${{ hashFiles('**/go.sum') }}


    - name: Install dependencies
      run: go mod tidy

    # - name: Run tests
    #   run: go test -v ./... # Run tests with verbose output

    - name: Build
      run: go build ./... # Build the project

    - name: Run linters
      run: go vet ./... && golint ./... # Run linting tools

    # - name: Upload Test Results
    #   if: success() # Only upload if tests were successful
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: test-results
    #     path: ./test-results/ # Specify the path where test results are stored (if applicable)

    - name: Notify on Failure
      if: failure() # Notify if there's a failure
      run: echo "Build failed. Please check the logs."
