# GitHub Action Workflow: .github/workflows/go-lint.yml -- 04.10.2024 -- Ralph Roth

name: Go Lint and Test

on:
  push:
    branches:
      - main   # Trigger this workflow on pushes to the `main` branch.
  pull_request:
    branches:
      - main   # Trigger this workflow for pull requests targeting the `main` branch.

jobs:
  lint-and-test:
    runs-on: ubuntu-latest  # Run on Ubuntu (you can change to other environments if needed)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.1'  # You can change the Go version if necessary

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/.golangci-lint-cache
          ./vendor
        key: go-mod-cache-${{ hashFiles('**/go.sum') }}

    - name: Install golangci-lint
      run: |
        curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.44.0/golangci-lint-1.44.0-linux-amd64.tar.gz | tar -xzv -C /tmp/
        sudo mv /tmp/golangci-lint-1.44.0-linux-amd64/golangci-lint /usr/local/bin/golangci-lint

    - name: Run golangci-lint
      run: golangci-lint run --timeout 5m

    - name: Run tests
      run: go test ./...
